### ISSUE TITLE
Download pictures

### ISSUE THREAD

**Issue by yadamz** [NuchangeInformatics/openmrs-module-dermimage#2]
- Please add feature to upload images and documents (text, doc, etc.)
- Please add a feature to download pictures and documents. 
- rename the name on dashboard from clinical Images to Images and Documents

**Comment by dermatologist** [comment]
Version 3.7 adds the download function. Other requests will be implemented soon.

**Comment by dermatologist** [comment]
Any file can be uploaded in 3.7. Closing the issue.
